name: localic
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  qlevar_router: ^1.10.2
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  shared_preferences: ^2.2.2
  file_picker: ^8.0.0+1
  q_overlay:
    git: https://github.com/SchabanBo/q_overlay.git
  dio: ^5.4.2
  flutter_hooks: ^0.20.5
  logger: ^2.2.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/example/localic.json