// Code generated at 2022-06-24 16:46:11.295525 by Qlevar Local Manager

class AppTranslation {
  static Map<String, Map<String, String>> translations = {
    "en": {
      "title": "Cool app", 
      "welcome": "welcome", 
      "cart_title": "Cart", 
      "cart_bar_res_de_not_available_rn": "Restaurant is not available at this time for delivery", 
      "cart_bar_go_to_cart": "Go to cart", 
      "cart_bar_items": "Items", 
      "cart_bar_address_msg": "Please Put Your Address To Make Order", 
      "cart_in_house_reload": "Reload", 
      "cart_in_house_pay": "Pay now", 
      "cart_in_house_confirm": "Confirm wish", 
      "cart_in_house_delete_from_wishlist": "Are you Sure you want to Delete @name @space from your order Wishlist ?", 
      "cart_in_house_empty": "Add your favorite food to the wishlist to order", 
      "cart_in_house_pay_when_done": "You can pay when all item has been served", 
      "cart_in_house_order_name": "Name", 
      "cart_in_house_order_number": "Number", 
      "cart_in_house_no_order": "You did not ordered anything yet", 
      "cart_in_house_order_name_picker_new": "Open new order", 
      "cart_in_house_order_name_picker_random": "Random name", 
      "cart_delivery_cart_empty": "Add your favorite food to the cart", 
      "cart_delivery_status_Created": "Created", 
      "cart_delivery_status_Ready": "Ready", 
      "cart_delivery_status_Accepted": "Prepare", 
      "cart_delivery_status_Delivered": "Delivered", 
      "cart_delivery_status_EnRoute": "EnRoute", 
      "cart_tip_thanks": "Thanks", 
      "cart_tip_add": "Add Tip to waiter", 
      "cart_tip_title": "Tip", 
      "cart_tip_note": "Note for the waiter", 
      "common_continue": "Continue", 
      "common_total": "Total", 
      "common_your_order": "Your order", 
      "common_delivery_cost": "Delivery Cost", 
      "common_delivery_time": "Delivery Time", 
      "drawer_main_page": "Main page", 
      "drawer_feedback": "Feedback", 
      "drawer_local_Language": "language"},

    "de": {
      "title": "Coole Anwendung", 
      "welcome": "willkommen", 
      "cart_title": "Wagen", 
      "cart_bar_res_de_not_available_rn": "Das Restaurant ist derzeit nicht für die Lieferung verfügbar", 
      "cart_bar_go_to_cart": "Zum Einkaufskorb gehen", 
      "cart_bar_items": "Artikel", 
      "cart_bar_address_msg": "Bitte geben Sie Ihre Adresse an, um eine Bestellung aufzugeben", 
      "cart_in_house_reload": "Neu laden", 
      "cart_in_house_pay": "Bezahlen", 
      "cart_in_house_confirm": "Wunsch bestätigen", 
      "cart_in_house_delete_from_wishlist": "Sind Sie sicher, dass Sie @name @space aus Ihrer Wunschliste löschen möchten?", 
      "cart_in_house_empty": "Fügen Sie Ihr Lieblingsessen der Wunschliste hinzu, um es zu bestellen", 
      "cart_in_house_pay_when_done": "Sie können bezahlen, wenn alle Artikel serviert wurden", 
      "cart_in_house_order_name": "Name", 
      "cart_in_house_order_number": "Nummer", 
      "cart_in_house_no_order": "Sie haben noch nichts bestellt", 
      "cart_in_house_order_name_picker_new": "Neue Bestellung öffnen", 
      "cart_in_house_order_name_picker_random": "Zufälliger Name", 
      "cart_delivery_cart_empty": "Fügen Sie Ihr Lieblingsessen dem Warenkorb hinzu", 
      "cart_delivery_status_Created": "Erstellt", 
      "cart_delivery_status_Ready": "Bereit", 
      "cart_delivery_status_Accepted": "Vorbereiten", 
      "cart_delivery_status_Delivered": "Geliefert", 
      "cart_delivery_status_EnRoute": "Unterwegs", 
      "cart_tip_thanks": "Vielen Dank", 
      "cart_tip_add": "Gib dem Kellner Trinkgeld", 
      "cart_tip_title": "Trinkgeld", 
      "cart_tip_note": "Hinweis für den Kellner", 
      "common_continue": "Fortsetzten", 
      "common_total": "Total", 
      "common_your_order": "Deine Bestellung", 
      "common_delivery_cost": "Versandkosten", 
      "common_delivery_time": "Lieferzeit", 
      "drawer_main_page": "Hauptseite", 
      "drawer_feedback": "Feedback", 
      "drawer_local_Language": "Sprache"},

    "ar": {
      "title": "تطبيق رائع", 
      "welcome": "أهلا بك", 
      "cart_title": "عربة التسوق", 
      "cart_bar_res_de_not_available_rn": "المطعم غير متوفر للتوصيل في هذا الوقت", 
      "cart_bar_go_to_cart": "اذهب إلى عربة التسوق", 
      "cart_bar_items": "العناصر", 
      "cart_bar_address_msg": "يرجى وضع عنوانك لتقديم الطلب", 
      "cart_in_house_reload": "تحديث", 
      "cart_in_house_pay": "دفع الحساب", 
      "cart_in_house_confirm": "أكد الطلب", 
      "cart_in_house_delete_from_wishlist": "هل أنت متأكد أنك تريد حذف@name @space من قائمة رغباتك طلبك؟", 
      "cart_in_house_empty": "أضف طعامك المفضل إلى قائمة الرغبات عند الطلب", 
      "cart_in_house_pay_when_done": "يمكنك الدفع عندما يتم تقديم كل العناصر", 
      "cart_in_house_order_name": "اسم", 
      "cart_in_house_order_number": "رقم", 
      "cart_in_house_no_order": "أنت لم تطلب أي شيء بعد", 
      "cart_in_house_order_name_picker_new": "فتح طلب جديد", 
      "cart_in_house_order_name_picker_random": "اسم عشوائي", 
      "cart_delivery_cart_empty": "أضف طعامك المفضل إلى عربة التسوق", 
      "cart_delivery_status_Created": "جديد", 
      "cart_delivery_status_Ready": "جاهز", 
      "cart_delivery_status_Accepted": "تحضير", 
      "cart_delivery_status_Delivered": "تم التوصيل", 
      "cart_delivery_status_EnRoute": "في المسار", 
      "cart_tip_thanks": "شكرًا", 
      "cart_tip_add": "أضف بقشيش للنادل", 
      "cart_tip_title": "بقشيش", 
      "cart_tip_note": "ملاحظة للنادل", 
      "common_continue": "متابعة", 
      "common_total": "المجموع", 
      "common_your_order": "طلبك", 
      "common_delivery_cost": "تكلفة التوصيل", 
      "common_delivery_time": "موعد التسليم", 
      "drawer_main_page": "الصفحة الرئيسية", 
      "drawer_feedback": "رايك بنا", 
      "drawer_local_Language": "اللغة"},
  };
}
  